version: 1.2.3.{build}
image: Visual Studio 2017
configuration: Release
environment:
 DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
- dotnet restore .\src\TupleExtensions\TupleExtensions.csproj
- msbuild .\src\TupleExtensions\TupleExtensions.csproj /t:pack /p:Configuration=Release /verbosity:minimal
- dotnet restore .\test\TupleExtensions.Tests\TupleExtensions.Tests.csproj
- dotnet build .\test\TupleExtensions.Tests\TupleExtensions.Tests.csproj
test_script:
- dotnet test .\test\TupleExtensions.Tests\TupleExtensions.Tests.csproj
artifacts:
- path: '**\*.nupkg'
