version: '1.2.4.{build}'
image: Visual Studio 2017
configuration: Release
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
  - dotnet build .\src\TupleExtensions\TupleExtensions.csproj
test_script:
  - dotnet test .\test\TupleExtensions.Tests\TupleExtensions.Tests.csproj
artifacts:
  - path: '**\*.nupkg'
